Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-09, with the labels that each got.

#533 Update device matrix pages
  CHANGELOG.md
  docs/benchmarks/device_compat_matrix/tensorrt.md
  docs/benchmarks/device_compat_matrix/tflite.md
  docs/benchmarks/device_matrix/drpai.md
  docs/benchmarks/device_matrix/openvino.md
  docs/benchmarks/device_matrix/tensorrt.md
  docs/benchmarks/device_matrix/tflite.md
Labels: documentation

#534 Add `no_weight_decay` and `overwrite` option in optimizer config
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/training.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/training.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/training.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/training.yaml
  config/training.yaml
  src/netspresso_trainer/optimizers/builder.py
  src/netspresso_trainer/pipelines/builder.py
Labels: enhancement

#535 Fix RandomCrop and segmentation dataset getitem
  CHANGELOG.md
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/segmentation.py
Labels: bug

#532 [!HOTFIX] delete install command for the optional requirements from Dockerfile
  CHANGELOG.md
  Dockerfile
Labels: bug

#531 [feat] Fuse batchNorm layer and enable reparameterization
  CHANGELOG.md
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/pipelines/train.py
Labels: enhancement

#538 Remove fx_model_path in model configuration
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/model.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/model.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/model.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/model.yaml
  config/model/efficientformer/efficientformer-l1-classification.yaml
  config/model/efficientformer/efficientformer-l1-detection.yaml
  config/model/efficientformer/efficientformer-l1-segmentation.yaml
  config/model/mixnet/mixnet-l-classification.yaml
  config/model/mixnet/mixnet-l-detection.yaml
  config/model/mixnet/mixnet-l-segmentation.yaml
  config/model/mixnet/mixnet-m-classification.yaml
  config/model/mixnet/mixnet-m-detection.yaml
  config/model/mixnet/mixnet-m-segmentation.yaml
  config/model/mixnet/mixnet-s-classification.yaml
  config/model/mixnet/mixnet-s-detection.yaml
  config/model/mixnet/mixnet-s-segmentation.yaml
  config/model/mobilenetv3/mobilenetv3-large-classification.yaml
  config/model/mobilenetv3/mobilenetv3-small-classification.yaml
  config/model/mobilenetv3/mobilenetv3-small-detection.yaml
  config/model/mobilenetv3/mobilenetv3-small-segmentation.yaml
  config/model/mobilenetv4/mobilenetv4-conv-large-classification.yaml
  config/model/mobilenetv4/mobilenetv4-conv-medium-classification.yaml
  config/model/mobilenetv4/mobilenetv4-conv-small-classification.yaml
  config/model/mobilenetv4/mobilenetv4-hybrid-large-classification.yaml
  config/model/mobilenetv4/mobilenetv4-hybrid-medium-classification.yaml
  config/model/mobilevit/mobilevit-s-classification.yaml
  config/model/pidnet/pidnet-s-segmentation.yaml
  config/model/resnet/resnet18-classification.yaml
  config/model/resnet/resnet34-classification.yaml
  config/model/resnet/resnet50-classification.yaml
  config/model/resnet/resnet50-detection.yaml
  config/model/resnet/resnet50-segmentation.yaml
  config/model/rtdetr/rtdetr-res18-detection.yaml
  config/model/rtdetr/rtdetr-res50-detection.yaml
  config/model/rtmpose/rtmpose-pose_estimation.yaml
  config/model/segformer/segformer-b0-segmentation.yaml
  config/model/vit/vit-tiny-classification.yaml
  config/model/yolo/yolo-fastest-v2-detection.yaml
  config/model/yolox/yolox-l-detection.yaml
  config/model/yolox/yolox-m-detection.yaml
  config/model/yolox/yolox-nano-detection.yaml
  config/model/yolox/yolox-s-detection.yaml
  config/model/yolox/yolox-tiny-detection.yaml
  config/model/yolox/yolox-x-detection.yaml
  demo/func/experiments.py
  docs/components/model/overview.md
  src/netspresso_trainer/evaluator_common.py
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/utils.py
  src/netspresso_trainer/trainer_common.py
  src/netspresso_trainer/utils/engine_utils.py
Labels: documentation, enhancement

#539 Enable ONNX model evaluation
  CHANGELOG.md
  src/netspresso_trainer/evaluator_common.py
  src/netspresso_trainer/evaluator_main.py
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/inferencer_main.py
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/utils.py
  src/netspresso_trainer/pipelines/base.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/trainer_common.py
  src/netspresso_trainer/utils/engine_utils.py
  src/netspresso_trainer/utils/stats.py
Labels: enhancement

#541 Add ONNX export tool
  CHANGELOG.md
  tools/onnx_convert.py
Labels: enhancement

#543 Fix no 'deploy' attribute error in fx model train phase
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: bug

#544 Fix bugs of PIDNet forward and saving
  CHANGELOG.md
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/full/experimental/pidnet.py
Labels: bug

#546 Add VOC 2012 dataset auto-downloader
  CHANGELOG.md
  config/data/local/voc2012_det.yaml
  docs/getting_started/dataset_preparation/local.md
  tools/open_dataset_tool/voc2012_det.py
Labels: documentation, enhancement
