Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-01, with the labels that each got.

#303 update CODEOWNERS
  .github/CODEOWNERS
Labels: no-changelog-update

#322 Simplify augmentation configuration hierarchy
  CHANGELOG.md
  config/augmentation/classification.yaml
  config/augmentation/detection.yaml
  config/augmentation/segmentation.yaml
  config/augmentation/template/common.yaml
  docs/components/augmentation/mixtransforms.md
  docs/components/augmentation/overview.md
  docs/components/augmentation/transforms.md
  mkdocs.yml
  src/netspresso_trainer/cfg/augmentation.py
  src/netspresso_trainer/dataloaders/augmentation/custom.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
  src/netspresso_trainer/dataloaders/augmentation/transforms.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/classification/dataset.py
Labels: refactoring

#323 Fix output_root_dir from fixed string to config value
  CHANGELOG.md
  src/netspresso_trainer/trainer_util.py
Labels: bug

#325 Add activation and dropout layer in FC
  CHANGELOG.md
  config/model/efficientformer/efficientformer-l1-classification.yaml
  config/model/mixnet/mixnet-l-classification.yaml
  config/model/mixnet/mixnet-m-classification.yaml
  config/model/mixnet/mixnet-s-classification.yaml
  config/model/mobilenetv3/mobilenetv3-small-classification.yaml
  config/model/mobilevit/mobilevit-s-classification.yaml
  config/model/resnet/resnet18-classification.yaml
  config/model/resnet/resnet34-classification.yaml
  config/model/resnet/resnet50-classification.yaml
  config/model/vit/vit-tiny-classification.yaml
  docs/benchmarks/benchmarks.md
  docs/models/heads/fc.md
  src/netspresso_trainer/cfg/model.py
  src/netspresso_trainer/models/heads/classification/core/fc.py
  src/netspresso_trainer/models/utils.py
Labels: enhancement

#327 [hotfix] Parsing version id from download url
  CHANGELOG.md
  src/netspresso_trainer/models/utils.py
Labels: bug

#329 Resize: Match longer side with input size and keep ratio
  CHANGELOG.md
  config/augmentation/classification.yaml
  config/augmentation/detection.yaml
  config/augmentation/segmentation.yaml
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/cfg/augmentation.py
  src/netspresso_trainer/dataloaders/augmentation/custom.py
Labels: enhancement

#332 Move custom transforms to each python module
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/__init__.py
  src/netspresso_trainer/dataloaders/augmentation/custom/__init__.py
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/augmentation/custom/mixing.py
  src/netspresso_trainer/dataloaders/augmentation/custom/mosaic.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
  src/netspresso_trainer/dataloaders/augmentation/transforms.py
Labels: refactoring

#334 Update Pad transform to receive target size of image
  CHANGELOG.md
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
Labels: enhancement, refactoring

#336 Add transform: HSVJitter
  CHANGELOG.md
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
Labels: enhancement

#337 Complete MosaicDetection
  CHANGELOG.md
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/cfg/augmentation.py
  src/netspresso_trainer/dataloaders/augmentation/custom/mosaic.py
  src/netspresso_trainer/dataloaders/detection/local.py
Labels: enhancement

#339 302 refactoring getitem
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/custom/mosaic.py
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/classification/huggingface.py
  src/netspresso_trainer/dataloaders/classification/local.py
  src/netspresso_trainer/dataloaders/detection/local.py
  src/netspresso_trainer/dataloaders/segmentation/huggingface.py
  src/netspresso_trainer/dataloaders/segmentation/local.py
Labels: refactoring
