Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-10, with the labels that each got.

#550 Add RandomResize2 transform
  CHANGELOG.md
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
Labels: documentation, enhancement

#551 Fix keyword error of segmentation training
  CHANGELOG.md
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: bug

#552 [feat] Add confidence score visualization
  CHANGELOG.md
  src/netspresso_trainer/loggers/visualizer.py
Labels: enhancement

#553 [misc] fix typo when saving optimizer state_dict
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: bug

#556 [docs] Update link to point directly to Docker setup page
  README.md
Labels: documentation, no-changelog-update

#559 [feat] Add `MultiStepLR`
  CHANGELOG.md
  docs/components/training/schedulers.md
  src/netspresso_trainer/schedulers/multi_step_lr.py
  src/netspresso_trainer/schedulers/registry.py
Labels: enhancement

#564 Refactoring metric modules
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  docs/components/logging.md
  src/netspresso_trainer/metrics/base.py
  src/netspresso_trainer/metrics/builder.py
  src/netspresso_trainer/metrics/classification/__init__.py
  src/netspresso_trainer/metrics/classification/metric.py
  src/netspresso_trainer/metrics/detection/__init__.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/metrics/pose_estimation/__init__.py
  src/netspresso_trainer/metrics/pose_estimation/metric.py
  src/netspresso_trainer/metrics/registry.py
  src/netspresso_trainer/metrics/segmentation/__init__.py
  src/netspresso_trainer/metrics/segmentation/metric.py
  src/netspresso_trainer/pipelines/builder.py
Labels: documentation, enhancement, refactoring

#568 Add class-wise metric analysis option
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  docs/components/logging.md
  src/netspresso_trainer/loggers/base.py
  src/netspresso_trainer/loggers/stdout.py
  src/netspresso_trainer/loggers/tensorboard.py
  src/netspresso_trainer/metrics/base.py
  src/netspresso_trainer/metrics/builder.py
  src/netspresso_trainer/metrics/classification/metric.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/metrics/pose_estimation/metric.py
  src/netspresso_trainer/metrics/segmentation/metric.py
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/record.py
Labels: enhancement

#565 [!HOTFIX] save dtype
  CHANGELOG.md
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/builder.py
Labels: bug

#566 [feat] Add ReLU6
  CHANGELOG.md
  src/netspresso_trainer/models/op/registry.py
Labels: enhancement

#563 [feat] Enable TFLite model evaluation
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/utils.py
Labels: enhancement

#567 Add feature to save last model artifacts
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: enhancement

#570 Add tabulating step for metric standard outputs
  CHANGELOG.md
  src/netspresso_trainer/loggers/stdout.py
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/pipelines/train.py
Labels: enhancement

#571 [fix] handle error when certain classes have no object in the dataset
  CHANGELOG.md
  src/netspresso_trainer/metrics/detection/metric.py
Labels: bug

#573 Get metric_key from primary_metric
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: bug

#574 Change field name save_criterion -> best_model_criterion
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  docs/components/logging.md
  src/netspresso_trainer/pipelines/train.py
Labels: refactoring

#572 [!HOTFIX] handle when there is no prediction
  CHANGELOG.md
  src/netspresso_trainer/metrics/detection/metric.py
Labels: bug
