Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-05, with the labels that each got.

#422 Adding darknet backbone for Yolo-Fastest
  config/model/yolo/yolo-fastest-detection.yaml
  src/netspresso_trainer/models/backbones/__init__.py
  src/netspresso_trainer/models/backbones/experimental/darknet.py
  src/netspresso_trainer/models/op/custom.py
  src/netspresso_trainer/models/op/registry.py
  src/netspresso_trainer/models/registry.py
Labels: enhancement

#435 Support file format of id_mapping field
  CHANGELOG.md
  README.md
  config/data/local/cifar100.yaml
  config/data/local/coco2017.yaml
  config/data/local/imagenet1k.yaml
  config/data/local/voc12.yaml
  config/data/local/voc12_grayscale_converted.yaml
  config/data/local/wflw.yaml
  docs/getting_started/dataset_preparation/local.md
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/pose_estimation.py
  src/netspresso_trainer/dataloaders/segmentation.py
  tools/open_dataset_tool/cifar100.py
  tools/open_dataset_tool/coco2017.py
  tools/open_dataset_tool/imagenet1k.py
  tools/open_dataset_tool/voc2012_seg.py
  tools/open_dataset_tool/wflw.py
Labels: documentation, enhancement

#437 Update docs to simple use.
  CHANGELOG.md
  docs/getting_started/simple_use.md
Labels: documentation

#439 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, no-changelog-update

#440 Minor typos and logging
  config/benchmark_examples/classification-imagenet1k-resnet34/environment.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/augmentation.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/training.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/training.yaml
  src/netspresso_trainer/pipelines/task_processors/base.py
Labels: no-changelog-update, refactoring

#444 Remove thop, replace MACs with FLOPs
  CHANGELOG.md
  requirements.txt
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/utils/record.py
  src/netspresso_trainer/utils/stats.py
Labels: refactoring

#447 Fix bug and update weights and benchmark scores for ViT and MobileViT
  CHANGELOG.md
  config/benchmark_examples/detection-coco2017-yolox_s/augmentation.yaml
  config/data/local/cityscapes.yaml
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/models/backbones/experimental/mobilevit.py
  src/netspresso_trainer/models/backbones/experimental/vit.py
  src/netspresso_trainer/models/op/custom.py
  src/netspresso_trainer/models/utils.py
  tools/open_dataset_tool/cityscapes.py
  tools/open_dataset_tool/imagenet1k.py
Labels: documentation, enhancement

#448 hotfix: handle best_epoch init error in TrainingSummary
  CHANGELOG.md
  src/netspresso_trainer/utils/record.py
Labels: bug

#452 Fix trivial typo from docs
  docs/components/augmentation/transforms.md
Labels: documentation, no-changelog-update
