Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-08, with the labels that each got.

#483 Update document Benchmarks & Deployment
  CHANGELOG.md
  docs/benchmarks/compression_compat_matrix.md
  docs/benchmarks/device_compat_matrix/tensorrt.md
  docs/benchmarks/device_compat_matrix/tflite.md
  docs/benchmarks/tflite_runtime_examples/yolox-s.md
  docs/components/model/postprocessor.md
  docs/components/model/postprocessors.md
  docs/models/backbones/cspdarknet.md
  docs/models/backbones/efficientformer.md
  docs/models/backbones/mixnet.md
  docs/models/backbones/mixtransformer.md
  docs/models/backbones/mobilenetv3.md
  docs/models/backbones/mobilevit.md
  docs/models/backbones/resnet.md
  docs/models/backbones/vit.md
  docs/models/fullmodels/pidnet.md
  docs/models/heads/allmlpdecoder.md
  docs/models/heads/anchordecoupledhead.md
  docs/models/heads/anchorfreedecoupledhead.md
  docs/models/heads/fc.md
  docs/models/heads/rtmcc.md
  mkdocs.yml
Labels: documentation

#485 Update postprocessor page
  CHANGELOG.md
  config/model/efficientformer/efficientformer-l1-classification.yaml
  config/model/mixnet/mixnet-l-classification.yaml
  config/model/mixnet/mixnet-m-classification.yaml
  config/model/mixnet/mixnet-s-classification.yaml
  config/model/mobilenetv3/mobilenetv3-large-classification.yaml
  config/model/mobilenetv3/mobilenetv3-small-classification.yaml
  config/model/mobilevit/mobilevit-s-classification.yaml
  config/model/resnet/resnet18-classification.yaml
  config/model/resnet/resnet34-classification.yaml
  config/model/resnet/resnet50-classification.yaml
  config/model/vit/vit-tiny-classification.yaml
  docs/components/model/postprocessors.md
  src/netspresso_trainer/postprocessors/classification.py
  train.py
Labels: documentation

#487 Write detailed status on training_summary
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/engine_utils.py
  src/netspresso_trainer/utils/record.py
Labels: enhancement

#490 Add RT-DETR: Encoder, Decoder
  CHANGELOG.md
  config/model/rtdetr/rtdetr-res18-detection.yaml
  src/netspresso_trainer/models/heads/detection/__init__.py
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/necks/__init__.py
  src/netspresso_trainer/models/necks/experimental/rtdetr_hybrid_encoder.py
  src/netspresso_trainer/models/registry.py
Labels: enhancement

#491 Add RT-DETR: Postprocessor
  CHANGELOG.md
  config/model/rtdetr/rtdetr-res18-detection.yaml
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/necks/experimental/rtdetr_hybrid_encoder.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/postprocessors/detection.py
  src/netspresso_trainer/postprocessors/registry.py
Labels: enhancement

#492 Add result vit-tiny on pi 4b
  CHANGELOG.md
  docs/benchmarks/device_compat_matrix/tflite.md
Labels: documentation

#493 Fix handling error in case of error occured in first epoch
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/record.py
Labels: bug

#495 Beta update: v1.0.1.b0
  CHANGELOG.md
  config/model/rtdetr/rtdetr-res18-detection.yaml
  docs/benchmarks/device_compat_matrix/tflite.md
  src/netspresso_trainer/models/heads/detection/__init__.py
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/necks/__init__.py
  src/netspresso_trainer/models/necks/experimental/rtdetr_hybrid_encoder.py
  src/netspresso_trainer/models/registry.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/postprocessors/detection.py
  src/netspresso_trainer/postprocessors/registry.py
  src/netspresso_trainer/utils/record.py
Labels: release

#482 Add Objects365 Dataset with Optimized Download Process
  CHANGELOG.md
  config/data/local/objects365.yaml
  docs/getting_started/dataset_preparation/local.md
  tools/open_dataset_tool/objects365.py
Labels: enhancement

#497 Add ResNet model parameters
  CHANGELOG.md
  config/model/resnet/resnet18-classification.yaml
  config/model/resnet/resnet34-classification.yaml
  config/model/resnet/resnet50-classification.yaml
  config/model/resnet/resnet50-detection.yaml
  config/model/resnet/resnet50-segmentation.yaml
  config/model/rtdetr/rtdetr-res18-detection.yaml
  src/netspresso_trainer/models/backbones/core/resnet.py
  src/netspresso_trainer/postprocessors/detection.py
Labels: enhancement

#499 Fix error in FLOPs computation
  CHANGELOG.md
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/pipelines/inference.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/stats.py
Labels: bug, documentation

#500 Add RT-DETR_res18 pretrained weights
  CHANGELOG.md
  config/model/rtdetr/rtdetr-res18-detection.yaml
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/models/utils.py
Labels: documentation, enhancement

#507 Add RT-DETR_res50
  CHANGELOG.md
  config/model/rtdetr/rtdetr-res50-detection.yaml
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/models/utils.py
Labels: documentation, enhancement

#503 Fix handling logical error when the data has invalid bbox.
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/detection.py
Labels: enhancement

#509 [!HOTFIX] Add depthwise params to yolox-s benchmarking model config
  config/benchmark_examples/detection-coco2017-yolox_s/model.yaml
Labels: bug, no-changelog-update

#504 Add RT-DETR: Data Augmentation
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
Labels: enhancement

#516 Add MobileNetV4 conv series
  CHANGELOG.md
  config/model/mobilenetv4/mobilenetv4-conv-large-classification.yaml
  config/model/mobilenetv4/mobilenetv4-conv-medium-classification.yaml
  config/model/mobilenetv4/mobilenetv4-conv-small-classification.yaml
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/models/backbones/__init__.py
  src/netspresso_trainer/models/backbones/experimental/mobilenetv4.py
  src/netspresso_trainer/models/heads/classification/__init__.py
  src/netspresso_trainer/models/heads/classification/core/fc.py
  src/netspresso_trainer/models/op/custom.py
  src/netspresso_trainer/models/registry.py
  src/netspresso_trainer/models/utils.py
  src/netspresso_trainer/postprocessors/registry.py
Labels: enhancement

#506 Add Gradient Clipping feature
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/training.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/training.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/training.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/training.yaml
  config/training.yaml
  docs/components/training/ema.md
  docs/components/training/gradient-clipping.md
  src/netspresso_trainer/pipelines/task_processors/base.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: enhancement

#517 Combine requirements and requirements-optional
  CHANGELOG.md
  requirements-optional.txt
  requirements.txt
Labels: refactoring

#513 [fix] scaling the total_loss when performing backward propagation
  CHANGELOG.md
  src/netspresso_trainer/losses/builder.py
Labels: refactoring

#518 [fix] Make total_loss to be a scalar tensor
  CHANGELOG.md
  src/netspresso_trainer/losses/detection/rtdetr.py
Labels: refactoring

#501 Add RT-DETR: denoising training
  CHANGELOG.md
  src/netspresso_trainer/losses/detection/rtdetr.py
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/heads/classification/core/fc.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_free_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_fastest_head.py
  src/netspresso_trainer/models/heads/pose_estimation/experimental/rtmcc.py
  src/netspresso_trainer/models/heads/segmentation/experimental/all_mlp_decoder.py
  src/netspresso_trainer/models/op/denoising.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: enhancement

#522 Extract ToTensor and Normalize to configuration file
  CHANGELOG.md
  config/augmentation/classification.yaml
  config/augmentation/detection.yaml
  config/augmentation/pose_estimation.yaml
  config/augmentation/segmentation.yaml
  config/benchmark_examples/classification-imagenet1k-resnet18/augmentation.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/augmentation.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/augmentation.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/augmentation.yaml
  docs/components/augmentation/transforms.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/augmentation/registry.py
  src/netspresso_trainer/dataloaders/augmentation/transforms.py
Labels: documentation, refactoring

#523 Fix return_stage_idx default value
  CHANGELOG.md
  src/netspresso_trainer/models/backbones/core/resnet.py
Labels: bug
