Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-04, with the labels that each got.

#391 Add dataset caching feature
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/classification/local.py
  src/netspresso_trainer/dataloaders/detection/local.py
  src/netspresso_trainer/dataloaders/pose_estimation/local.py
  src/netspresso_trainer/dataloaders/segmentation/local.py
  src/netspresso_trainer/dataloaders/utils/loader.py
  src/netspresso_trainer/pipelines/builder.py
  src/netspresso_trainer/pipelines/task_processors/base.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: enhancement

#392 Add mixed precision training
  CHANGELOG.md
  src/netspresso_trainer/losses/builder.py
  src/netspresso_trainer/pipelines/task_processors/base.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: enhancement

#393 Add yolox weights init
  CHANGELOG.md
  src/netspresso_trainer/models/backbones/experimental/darknet.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_free_decoupled_head.py
  src/netspresso_trainer/models/necks/experimental/yolopafpn.py
Labels: enhancement

#394 Fix graphmodule training best save bug
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: bug

#395 Minor fixes
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/detection/local.py
  src/netspresso_trainer/postprocessors/detection.py
Labels: refactoring

#396 Add YOLOX l1 loss activation option
  CHANGELOG.md
  config/model/yolox/yolox-s-detection.yaml
  src/netspresso_trainer/losses/builder.py
  src/netspresso_trainer/losses/detection/yolox.py
  src/netspresso_trainer/pipelines/builder.py
Labels: enhancement

#397 Mosaic update strategy
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/custom/mosaic.py
  src/netspresso_trainer/losses/detection/yolox.py
Labels: refactoring

#398 Refactor random resize
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/custom/image_proc.py
  src/netspresso_trainer/dataloaders/utils/loader.py
  src/netspresso_trainer/trainer_common.py
Labels: refactoring

#399 Specify input size for onnx export and remove augmentation.img_size
  CHANGELOG.md
  config/augmentation/classification.yaml
  config/augmentation/detection.yaml
  config/augmentation/pose_estimation.yaml
  config/augmentation/segmentation.yaml
  config/augmentation/template/common.yaml
  config/logging.yaml
  config/model/segformer/segformer-b0-segmentation.yaml
  src/netspresso_trainer/dataloaders/augmentation/transforms.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/utils/loader.py
  src/netspresso_trainer/evaluator_common.py
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/losses/common.py
  src/netspresso_trainer/losses/detection/retinanet.py
  src/netspresso_trainer/losses/pose_estimation/rtmcc.py
  src/netspresso_trainer/losses/segmentation/pidnet.py
  src/netspresso_trainer/metrics/builder.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/heads/segmentation/experimental/all_mlp_decoder.py
  src/netspresso_trainer/pipelines/base.py
  src/netspresso_trainer/pipelines/builder.py
  src/netspresso_trainer/trainer_common.py
Labels: refactoring

#401 Update issue and pr template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#402 Refactoring metric modules
  CHANGELOG.md
  src/netspresso_trainer/metrics/base.py
  src/netspresso_trainer/metrics/builder.py
  src/netspresso_trainer/metrics/classification/metric.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/metrics/pose_estimation/metric.py
  src/netspresso_trainer/metrics/segmentation/metric.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/record.py
Labels: bug, refactoring

#406 Add NetsPresso Trainer YOLOX pretrained weights
  CHANGELOG.md
  docs/benchmarks/benchmarks.md
  src/netspresso_trainer/models/utils.py
Labels: documentation, enhancement

#405 Add docs-deploy.yml action
  .github/workflows/docs-deploy.yml
  CHANGELOG.md
Labels: documentation, enhancement

#408 Unify gradio demo
  CHANGELOG.md
  demo/app.py
  demo/docs/description_augmentation.md
  demo/docs/description_pynetspresso.md
  demo/docs/description_scheduler.md
  demo/func/__init__.py
  demo/func/augmentation.py
  demo/func/experiments.py
  demo/func/main.py
  demo/func/pynetspresso.py
  demo/func/scheduler.py
  demo/gradio_augmentation.py
  demo/gradio_lr_scheduler.py
  demo/tab/__init__.py
  demo/tab/compressor.py
  demo/tab/experiments.py
  demo/tab/home/__init__.py
  demo/tab/home/augmentation.py
  demo/tab/home/dataset.py
  demo/tab/home/main.py
  demo/tab/home/model.py
  demo/tab/home/scheduler.py
  demo/tab/home/train.py
  requirements-optional.txt
  scripts/run_gradio.sh
  scripts/run_simulator_augmentation.sh
  scripts/run_simulator_lr_scheduler.sh
  src/netspresso_trainer/models/necks/experimental/fpn.py
Labels: enhancement

#410 Update docs
  CHANGELOG.md
  README.md
  docs/components/augmentation/transforms.md
  docs/components/model/losses.md
  docs/getting_started/installation/docker_installation.md
  docs/getting_started/installation/installation.md
  docs/getting_started/simple_use.md
  docs/installation.md
  mkdocs.yml
  scripts/example_train.sh
Labels: documentation

#412 Update issue template
  .github/ISSUE_TEMPLATE/bug_report_template.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/project-issue.md
Labels: documentation, no-changelog-update

#414 [hotfix] Eval and Infer don't have training conf
  src/netspresso_trainer/pipelines/task_processors/base.py
Labels: bug, no-changelog-update

#417 Add dataset validation step and refactoring data modules
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/augmentation/README.md
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/classification/__init__.py
  src/netspresso_trainer/dataloaders/classification/dataset.py
  src/netspresso_trainer/dataloaders/classification/huggingface.py
  src/netspresso_trainer/dataloaders/classification/local.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/detection/__init__.py
  src/netspresso_trainer/dataloaders/detection/coco.yaml
  src/netspresso_trainer/dataloaders/detection/dataset.py
  src/netspresso_trainer/dataloaders/pose_estimation.py
  src/netspresso_trainer/dataloaders/pose_estimation/__init__.py
  src/netspresso_trainer/dataloaders/pose_estimation/dataset.py
  src/netspresso_trainer/dataloaders/registry.py
  src/netspresso_trainer/dataloaders/segmentation.py
  src/netspresso_trainer/dataloaders/segmentation/__init__.py
  src/netspresso_trainer/dataloaders/segmentation/dataset.py
  src/netspresso_trainer/dataloaders/segmentation/huggingface.py
  src/netspresso_trainer/dataloaders/segmentation/local.py
  src/netspresso_trainer/dataloaders/utils/collate_fn.py
  src/netspresso_trainer/dataloaders/utils/misc.py
  src/netspresso_trainer/evaluator_common.py
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/trainer_common.py
Labels: enhancement, refactoring

#419 [hotfix] Fix dataset path check
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/builder.py
Labels: bug

#420 Save training summary at every end of epochs
  CHANGELOG.md
  src/netspresso_trainer/pipelines/train.py
Labels: refactoring

#428 Fix test directory check line
  CHANGELOG.md
  src/netspresso_trainer/dataloaders/builder.py
Labels: bug

#430 Add various dataset examples
  CHANGELOG.md
  README.md
  config/data/coco_yolo.yaml
  config/data/huggingface/beans.yaml
  config/data/huggingface/chest-xray-classification.yaml
  config/data/huggingface/cifar100.yaml
  config/data/huggingface/sidewalk-semantic.yaml
  config/data/huggingface/skin_cancer.yaml
  config/data/huggingface/wikiart-artist.yaml
  config/data/local/chess.yaml
  config/data/local/cifar100.yaml
  config/data/local/coco2017.yaml
  config/data/local/imagenet1k.yaml
  config/data/local/rcv-workshop-iccv2023.yaml
  config/data/local/traffic-sign.yaml
  config/data/local/voc12.yaml
  config/data/local/voc12_grayscale_converted.yaml
  config/data/local/wflw.yaml
  config/data/sample_classification_label.csv
  docs/components/data.md
  docs/components/overview.md
  docs/getting_started/dataset_preparation/huggingface.md
  docs/getting_started/dataset_preparation/local.md
  mkdocs.yml
  requirements-optional.txt
  tools/open_dataset_tool/cifar100.py
  tools/open_dataset_tool/coco2017.py
  tools/open_dataset_tool/imagenet1k.py
  tools/open_dataset_tool/voc2012_seg.py
Labels: documentation, enhancement

#431 Minor docs update
  docs/components/data.md
  docs/getting_started/dataset_preparation/huggingface.md
  docs/getting_started/dataset_preparation/local.md
Labels: documentation, no-changelog-update

#429 Adding yolov3 head for Yolo-Fastest
  config/model/yolo-fastest/yolo-fastest.yaml
  src/netspresso_trainer/models/heads/detection/__init__.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_fastest_head.py
  src/netspresso_trainer/models/registry.py
Labels: enhancement

#432 Set id_mapping through text file
  CHANGELOG.md
  config/data/local/cifar100.yaml
  config/data/local/coco2017.yaml
  config/data/local/imagenet1k.yaml
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/pose_estimation.py
  src/netspresso_trainer/dataloaders/segmentation.py
  tools/open_dataset_tool/cifar100.py
  tools/open_dataset_tool/coco2017.py
  tools/open_dataset_tool/imagenet1k.py
Labels: enhancement
