Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2024-11, with the labels that each got.

#579 Add features to log precision and recall metric for each class. (detection task)
  CHANGELOG.md
  src/netspresso_trainer/metrics/builder.py
  src/netspresso_trainer/metrics/detection/__init__.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/metrics/registry.py
Labels: enhancement

#581 [refactor] RT-DETR hybrid encoder
  CHANGELOG.md
  src/netspresso_trainer/models/necks/experimental/rtdetr_hybrid_encoder.py
  src/netspresso_trainer/models/op/custom.py
Labels: refactoring

#583 [refactor] Pooling layers
  CHANGELOG.md
  src/netspresso_trainer/models/backbones/core/resnet.py
  src/netspresso_trainer/models/backbones/experimental/shufflenetv2.py
  src/netspresso_trainer/models/op/base_metaformer.py
  src/netspresso_trainer/models/op/custom.py
  src/netspresso_trainer/models/op/pidnet.py
  src/netspresso_trainer/models/op/registry.py
Labels: refactoring

#586 Implement SPP Blocks
  CHANGELOG.md
  src/netspresso_trainer/models/op/custom.py
Labels: enhancement

#587 Refactor: Consolidate Bounding box Transformation and IoU Calculation Functions
  CHANGELOG.md
  src/netspresso_trainer/losses/detection/rtdetr.py
  src/netspresso_trainer/losses/detection/yolo.py
  src/netspresso_trainer/losses/detection/yolox.py
  src/netspresso_trainer/postprocessors/detection.py
  src/netspresso_trainer/utils/bbox_utils.py
Labels: enhancement, refactoring

#588 Update Pool -> Pool2d
  src/netspresso_trainer/models/backbones/core/resnet.py
  src/netspresso_trainer/models/backbones/experimental/shufflenetv2.py
  src/netspresso_trainer/models/op/base_metaformer.py
  src/netspresso_trainer/models/op/pidnet.py
Labels: bug, no-changelog-update
