Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2025-07, with the labels that each got.

#630 Add configuration files for YOLOv9 Tiny model training from scratch
  config/benchmark_examples/detection-coco2017-yolov9_tiny/augmentation.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/data.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/environment.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/logging.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/model.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/training.yaml
Labels: enhancement, no-changelog-update

#632 Add EXIR exporting feature
  CHANGELOG.md
  Dockerfile
  README.md
  docs/getting_started/installation/installation.md
  requirements.txt
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/exir.py
  src/netspresso_trainer/utils/logger.py
  tools/exir_convert.py
Labels: enhancement

#633 Release: v1.4.1
  CHANGELOG.md
  Dockerfile
  README.md
  config/benchmark_examples/detection-coco2017-yolov9_tiny/augmentation.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/data.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/environment.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/logging.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/model.yaml
  config/benchmark_examples/detection-coco2017-yolov9_tiny/training.yaml
  config/environment.yaml
  config/model/yolov9/yolov9_c-detection.yaml
  config/model/yolov9/yolov9_m-detection.yaml
  config/model/yolov9/yolov9_s-detection.yaml
  config/model/yolov9/yolov9_tiny-detection.yaml
  docs/benchmarks/benchmarks.md
  docs/getting_started/installation/installation.md
  requirements.txt
  src/netspresso_trainer/VERSION
  src/netspresso_trainer/loggers/mlflow.py
  src/netspresso_trainer/models/utils.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/exir.py
  src/netspresso_trainer/utils/logger.py
  tools/exir_convert.py
Labels: release
