Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2025-03, with the labels that each got.

#611 [refactor] delete label_size, targets parameters from forward method across models
  CHANGELOG.md
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/heads/classification/core/fc.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_free_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_fastest_head.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_head.py
  src/netspresso_trainer/models/heads/pose_estimation/experimental/rtmcc.py
  src/netspresso_trainer/models/heads/segmentation/experimental/all_mlp_decoder.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
Labels: refactoring

#610 [!HOTFIX] change padding fill value to 114 of yolox augmentation config
  CHANGELOG.md
  config/benchmark_examples/detection-coco2017-yolox_s/augmentation.yaml
Labels: bug

#608 [Fix] Add cache_data option
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/environment.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/environment.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/environment.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/environment.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/environment.yaml
  config/environment.yaml
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/pose_estimation.py
  src/netspresso_trainer/dataloaders/segmentation.py
  src/netspresso_trainer/dataloaders/utils/loader.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/environment.py
Labels: enhancement

#613 Torch versionup
  CHANGELOG.md
  Dockerfile
  README.md
  docs/getting_started/installation/installation.md
  requirements.txt
Labels: enhancement

#614 Minor update: v1.2.0 release
  CHANGELOG.md
  Dockerfile
  README.md
  config/benchmark_examples/classification-imagenet1k-resnet18/environment.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/environment.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/environment.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/environment.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/augmentation.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/environment.yaml
  config/environment.yaml
  docs/getting_started/installation/installation.md
  requirements.txt
  src/netspresso_trainer/VERSION
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/pose_estimation.py
  src/netspresso_trainer/dataloaders/segmentation.py
  src/netspresso_trainer/dataloaders/utils/loader.py
  src/netspresso_trainer/models/base.py
  src/netspresso_trainer/models/heads/classification/core/fc.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/anchor_free_decoupled_head.py
  src/netspresso_trainer/models/heads/detection/experimental/rtdetr_head.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_fastest_head.py
  src/netspresso_trainer/models/heads/detection/experimental/yolo_head.py
  src/netspresso_trainer/models/heads/pose_estimation/experimental/rtmcc.py
  src/netspresso_trainer/models/heads/segmentation/experimental/all_mlp_decoder.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/utils/environment.py
Labels: release

#615 [AIE-39] Add a new MLFlow tracking feature
  .gitignore
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  docs/benchmarks/benchmarks.md
  docs/components/logging.md
  src/netspresso_trainer/loggers/base.py
  src/netspresso_trainer/loggers/mlflow.py
  src/netspresso_trainer/metrics/classification/metric.py
  src/netspresso_trainer/pipelines/train.py
Labels: enhancement

#617 Minor update: v1.3.0 release
  .gitignore
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  docs/benchmarks/benchmarks.md
  docs/components/logging.md
  src/netspresso_trainer/VERSION
  src/netspresso_trainer/loggers/base.py
  src/netspresso_trainer/loggers/mlflow.py
  src/netspresso_trainer/metrics/classification/metric.py
  src/netspresso_trainer/pipelines/train.py
Labels: release
