Repository Nota-NetsPresso/netspresso-trainer, pull requests merged in 2025-05, with the labels that each got.

#621 [DF-237] Add feature to register ONNX model to mlflow registry
  CHANGELOG.md
  requirements.txt
  src/netspresso_trainer/loggers/mlflow.py
  src/netspresso_trainer/pipelines/train.py
Labels: enhancement

#622 Loosen torch version coverage
  CHANGELOG.md
  requirements.txt
Labels: hotfix, refactoring

#623 Release: v1.3.1
  CHANGELOG.md
  requirements.txt
  src/netspresso_trainer/VERSION
  src/netspresso_trainer/loggers/mlflow.py
  src/netspresso_trainer/losses/detection/yolo.py
  src/netspresso_trainer/models/builder.py
  src/netspresso_trainer/models/utils.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/postprocessors/detection.py
Labels: release

#625 Sample logging refactoring
  CHANGELOG.md
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/loggers/base.py
  src/netspresso_trainer/loggers/builder.py
  src/netspresso_trainer/loggers/tensorboard.py
  src/netspresso_trainer/loggers/visualizer.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/pipelines/builder.py
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/pipelines/inference.py
  src/netspresso_trainer/pipelines/task_processors/base.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/postprocessors/detection.py
  src/netspresso_trainer/utils/engine_utils.py
  src/netspresso_trainer/utils/protocols.py
Labels: refactoring

#627 fix cls postprocessor bug
  CHANGELOG.md
  src/netspresso_trainer/postprocessors/classification.py
Labels: bug

#628 Release: v1.4.0
  CHANGELOG.md
  Dockerfile
  config/benchmark_examples/classification-imagenet1k-resnet18/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet34/logging.yaml
  config/benchmark_examples/classification-imagenet1k-resnet50/logging.yaml
  config/benchmark_examples/detection-coco2017-yolo_fastest_v2/logging.yaml
  config/benchmark_examples/detection-coco2017-yolox_s/logging.yaml
  config/logging.yaml
  src/netspresso_trainer/VERSION
  src/netspresso_trainer/dataloaders/base.py
  src/netspresso_trainer/dataloaders/builder.py
  src/netspresso_trainer/dataloaders/classification.py
  src/netspresso_trainer/dataloaders/detection.py
  src/netspresso_trainer/dataloaders/segmentation.py
  src/netspresso_trainer/dataloaders/utils/collate_fn.py
  src/netspresso_trainer/inferencer_common.py
  src/netspresso_trainer/loggers/base.py
  src/netspresso_trainer/loggers/builder.py
  src/netspresso_trainer/loggers/tensorboard.py
  src/netspresso_trainer/loggers/visualizer.py
  src/netspresso_trainer/metrics/detection/metric.py
  src/netspresso_trainer/pipelines/builder.py
  src/netspresso_trainer/pipelines/evaluation.py
  src/netspresso_trainer/pipelines/inference.py
  src/netspresso_trainer/pipelines/task_processors/base.py
  src/netspresso_trainer/pipelines/task_processors/classification.py
  src/netspresso_trainer/pipelines/task_processors/detection.py
  src/netspresso_trainer/pipelines/task_processors/pose_estimation.py
  src/netspresso_trainer/pipelines/task_processors/segmentation.py
  src/netspresso_trainer/pipelines/train.py
  src/netspresso_trainer/postprocessors/classification.py
  src/netspresso_trainer/postprocessors/detection.py
  src/netspresso_trainer/utils/engine_utils.py
  src/netspresso_trainer/utils/protocols.py
Labels: release
